openapi: 3.0.0
info:
  title: Comment
  version: 1.0
  description: Collection for commenting functionalities.
paths:
  /comment/editComment:
    put:
      summary: Edit Comment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                commentId:
                  type: string
              required:
                - commentId
      responses:
        '200':
          description: Successful operation
  /comment/delete:
    delete:
      summary: Delete Comment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                commentId:
                  type: string
              required:
                - commentId
      responses:
        '200':
          description: Successful operation
  /comment/hide:
    put:
      summary: Hide Comment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                commentId:
                  type: string
                hidden:
                  type: boolean
              required:
                - commentId
                - hidden
      responses:
        '200':
          description: Successful operation
