openapi: 3.0.0
info:
  title: All Functionalities
  version: "1.0"
  description: Collection for managing posts, comments, homepage, notifications, subreddit, and settings functionalities.
paths:
  /post/getAllPosts:
    get:
      summary: Get All Posts
      responses:
        '200':
          description: Successful operation

  /post/upvote:
    put:
      summary: Upvote
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                postId:
                  type: string
              required:
                - postId
      responses:
        '200':
          description: Successful operation

  /post/downvote:
    put:
      summary: Downvote
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                postId:
                  type: string
              required:
                - postId
      responses:
        '200':
          description: Successful operation

  /post/save:
    put:
      summary: Save Post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                postId:
                  type: string
              required:
                - postId
      responses:
        '200':
          description: Successful operation

  /post/unsave:
    put:
      summary: Unsave Post
      responses:
        '200':
          description: Successful operation

  /post/editPost:
    put:
      summary: Edit Post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                postId:
                  type: string
              required:
                - postId
      responses:
        '200':
          description: Successful operation

  /posts/lockPost:
    put:
      summary: Lock Post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                postId:
                  type: string
                isLocked:
                  type: boolean
              required:
                - postId
                - isLocked
      responses:
        '200':
          description: Successful operation

  /posts/unlockPost:
    put:
      summary: Unlock Post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                postId:
                  type: string
                isLocked:
                  type: boolean
              required:
                - postId
                - isLocked
      responses:
        '200':
          description: Successful operation

  /posts/delete:
    delete:
      summary: Delete Post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                postId:
                  type: string
              required:
                - postId
      responses:
        '200':
          description: Successful operation

  /post/hide:
    put:
      summary: Hide Post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                postId:
                  type: string
                hidden:
                  type: boolean
              required:
                - postId
                - hidden
      responses:
        '200':
          description: Successful operation

  /comment/editComment:
    put:
      summary: Edit Comment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                commentId:
                  type: string
              required:
                - commentId
      responses:
        '200':
          description: Successful operation

  /comment/delete:
    delete:
      summary: Delete Comment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                commentId:
                  type: string
              required:
                - commentId
      responses:
        '200':
          description: Successful operation

  /comment/hide:
    put:
      summary: Hide Comment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                commentId:
                  type: string
                hidden:
                  type: boolean
              required:
                - commentId
                - hidden
      responses:
        '200':
          description: Successful operation

  /post/sorting:
    get:
      summary: Sorting
      parameters:
        - in: query
          name: Hot
          schema:
            type: boolean
          required: false
        - in: query
          name: New
          schema:
            type: boolean
          required: false
        - in: query
          name: Top
          schema:
            type: boolean
          required: false
        - in: query
          name: Random
          schema:
            type: boolean
          required: false
      responses:
        '200':
          description: Successful operation

  /post/createPost:
    post:
      summary: Create Post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                text:
                  type: string
                media:
                  type: string
                link:
                  type: string
                NSFW:
                  type: boolean
                replyNotifications:
                  type: boolean
              required:
                - title
                - text
      responses:
        '200':
          description: Successful operation

  /subriddit/topCommunities:
    get:
      summary: Top Communities
      responses:
        '200':
          description: Successful operation

  /subriddit/joinCommunity:
    post:
      summary: Join Community
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                subRedditID:
                  type: string
              required:
                - subRedditID
      responses:
        '200':
          description: Successful operation

  /subriddit/viewCommunity:
    get:
      summary: View Community
      responses:
        '200':
          description: Successful operation

  /notification/newRequest:
    get:
      summary: New Request
      responses:
        '200':
          description: Successful operation

  /subreddit/sorting:
    get:
      summary: Sorting
      parameters:
        - in: query
          name: Hot
          schema:
            type: boolean
          required: false
        - in: query
          name: New
          schema:
            type: boolean
          required: false
        - in: query
          name: Top
          schema:
            type: boolean
          required: false
        - in: query
          name: Random
          schema:
            type: boolean
          required: false
      responses:
        '200':
          description: Successful operation

  /subreddit/createPost:
    post:
      summary: Create Post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                text:
                  type: string
                media:
                  type: string
                link:
                  type: string
                NSFW:
                  type: boolean
                replyNotifications:
                  type: boolean
              required:
                - title
                - text
      responses:
        '200':
          description: Successful operation

  /settings/userSettings:
    put:
      summary: Account Settings
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                gender:
                  type: string
                deleteAccount:
                  type: boolean
              required:
                - email
                - gender
                - deleteAccount
      responses:
        '200':
          description: Successful operation

  /settings/profileSettings:
    put:
      summary: Profile Settings
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                displayName:
                  type: string
                about:
                  type: string
                link:
                  type: string
                appName:
                  type: string
                avatarImage:
                  type: string
                bannerImage:
                  type: string
                NSFW:
                  type: boolean
                allowFollow:
                  type: boolean
                contentVisibility:
                  type: boolean
                communitiesVisibility:
                  type: boolean
                clearHistory:
                  type: boolean
              required:
                - displayName
                - about
                - link
                - appName
                - avatarImage
                - bannerImage
                - NSFW
                - allowFollow
                - contentVisibility
                - communitiesVisibility
                - clearHistory
      responses:
        '200':
          description: Successful operation

  /settings/safetyAndPrivacySettings:
    put:
      summary: Safety and Privacy Settings
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                blockUser:
                  type: string
                muteCommunity:
                  type: string
              required:
                - blockUser
                - muteCommunity
      responses:
        '200':
          description: Successful operation

  /settings/feedSettings:
    put:
      summary: Feed Settings
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                adultContent:
                  type: boolean
                autoPlayMedia:
                  type: boolean
                communityThemes:
                  type: boolean
                communityContentSort:
                  type: string
                globalContentView:
                  type: string
                postsInNewTab:
                  type: boolean
              required:
                - adultContent
                - autoPlayMedia
                - communityThemes
                - communityContentSort
                - globalContentView
                - postsInNewTab
      responses:
        '200':
          description: Successful operation

  /settings/notificationsSettings:
    put:
      summary: Notifications Settings
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                mentions:
                  type: boolean
                comments:
                  type: boolean
                upVotesPosts:
                  type: boolean
                upVotesComments:
                  type: boolean
                repliesComments:
                  type: boolean
                newFollowers:
                  type: boolean
                postsFollowed:
                  type: boolean
              required:
                - mentions
                - comments
                - upVotesPosts
                - upVotesComments
                - repliesComments
                - newFollowers
                - postsFollowed
      responses:
        '200':
          description: Successful operation
